language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - nightly
install:
    - pip install .
    - pip install prospector
script:
    - python setup.py nosetests
    - prospector -s veryhigh --doc-warnings gobble
