language: python
sudo: false
python:
    - "3.3"
    - "3.4"
    - nightly
install:
    - pip install .
    - pip install prospector
script:
    - python setup.py nosetests
    - prospector -s medium --doc-warnings gobble
